# Generated by Django 4.1.3 on 2022-11-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('rate', models.IntegerField(verbose_name='Exchange rate to the USD')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Exchange rate on the date')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.IntegerField(verbose_name='Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('tax', models.IntegerField(verbose_name='Tax')),
                ('currency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('sum', models.IntegerField(verbose_name='Order sum')),
                ('discount', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(verbose_name='Tax')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Item quantity')),
                ('sum', models.IntegerField(verbose_name='Items price')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('tax', models.IntegerField(verbose_name='Tax')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.item')),
                ('order_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.order', verbose_name='Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.orderitemslist'),
        ),
    ]
