# Generated by Django 4.1.3 on 2022-11-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0002_alter_currency_options_alter_orderitemslist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
