# Generated by Django 4.1.3 on 2022-11-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0003_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(default='VAT', max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Exchange rate on the date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_app.tax', verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderitemslist',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tax'),
        ),
    ]
