# Generated by Django 4.1.3 on 2022-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0004_remove_tax_order_tax_name_alter_currency_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Item id'),
        ),
    ]
